### ISSUE TITLE
Cannot open fiber tracking section

### ISSUE THREAD

**Issue by takhs91** [maksteel/dsi-studio-docker#1]
Hi! what a coincidence I was also working on that yesterday. 

Although I had a different approach since I was simply copying the binary instead of running it inside the container.

What do you think that are the pros and cons from running it inside than use it just for building?

I tried to run it as you suggested but gettin an 
`Unrecognized OpenGL version` when trying to open the fiber tracking section
Any suggestions?

**Comment by maksteel** [comment]
Are you running it on Linux Host?
or
If you are on Mac OSX host try these steps: https://www.visitusers.org/index.php?title=Re-enabling_INdirect_glx_on_your_X_server

It seems though Indirect GLX rendering is disabled on your host machine.

**Comment by takhs91** [comment]
I am running it on a laptop running Linux Mint 18 64-bit  4.4.0-21-generic. OK I guess it will be an option somewhere in X Server config. I'll look it up.

**Comment by maksteel** [comment]
Sure, try installing boost, opengl and qt libs on your laptop.
```
sudo apt-get install qt5-qmake qt5-default libboost-all-dev \
                     libqt5opengl5-dev libgl1-mesa-dev \
                     libglu1-mesa-dev freeglut3-dev mesa-utils

```
