### ISSUE TITLE
note about ssh -X: --net host -v $HOME/.Xauthority:/root/.Xauthority:rw

### ISSUE THREAD

**Issue by WillForan** [maksteel/dsi-studio-docker#4]
If I `ssh -X` to a the docker host, I need the additional docker options `--net host -v $HOME/.Xauthority:/root/.Xauthority:rw` to get the GUI on X11 forwarding over ssh in docker. This in addition to `host +x` on local.

The `host +x` in the readme is super helpful. Does a ssh+docker parameter tip fall on that side of the helpful vs intimidating/too niche balance?

**Comment by maksteel** [comment]
changes are merged
